- fuse/nodefs/fsconnector.go
- fuse/nodefs/fsmount.go
- fuse/nodefs/fsops.go
- fuse/nodefs/handle.go
- fuse/nodefs/handle_test.go
- fuse/nodefs/inode.go
- fuse/print.go
Move the generation field from nodefs/FileSystemConnector to handleMap.
Have handleMap.Register() return both the inode number and the generation number.
Increment the generation number whenever Register() reuses a previously-used node ID.
Add test.
> Use generation numbers properly

- fuse/nodefs/files.go
- fuse/nodefs/files_darwin.go
- fuse/nodefs/files_linux.go
- fuse/nodefs/files_test.go
syscall.NsecToTimespec does not work properly for times
before 1970, see https://github.com/golang/go/issues/12777
This caused xfstests generic/258 to fail.
Fixes issue #58.
Additionally, this fixes a bug in line 46 where `a` was used instead of `m`
> loopback: Replace buggy syscall.NsecToTimeval()

- fuse/nodefs/fsconnector.go
- fuse/nodefs/fsmount.go
- fuse/nodefs/fsops.go
"out.Ino" is the user-facing inode number that is displayed by "ls -li".
This change allows loopback filesystems to expose the inode number of
the underlying filesystem.
As a "real" inode number, this one is stable for the lifetime of the file,
even across remounts.
libfuse has the `use_ino` option that allows the inode numbers to be set arbitrarily as well. This has been used by EncFS for years.
The Linux kernel stores the inode number in `orig_ino`. Grepping in `fs/fuse` shows that it is only read once in `fuse_update_attributes`, and only if the `stat` argument is not NULL. There is only one caller that passes that argument: `fuse_getattr`.
In short, the kernel does not use the inode number for anything but reporting it via `stat()`, hence setting the inode number is safe.
This …
> nodefs: do not overwrite the "out.Ino" inode number if it is already set

- fuse/nodefs/files_linux.go
- fuse/pathfs/loopback_linux.go
- fuse/test/loopback_linux_test.go
time.Unix() returns int64 regardless of target platform but field of timeval is
defined as int32 values on ubuntu-32bit
NsecToTimeval has a nanosecond problem(negative value) before epoch but still can use a second field
> fix compilation error on ubuntu-32bit

- all.bash
- fuse/pathfs/pathfs.go
If the file handle is specified we should use it instead of
picking one at random.
Fixes #95.
> Have pathInode.Truncate and friends use the file handle, if available

- fuse/mount_darwin.go
I synced up recently and was seeing this error on Darwin:
```
2016/07/31 01:16:54 Dispatch 1: WRITE, NodeId: 10.  65536 bytes
2016/07/31 01:16:54 Serialize 1: WRITE code: OK value: 
2016/07/31 01:16:54 writer: Write/Writev failed, err: 9=bad file descriptor. opcode: WRITE
2016/07/31 01:16:54 Failed to read from fuse conn: 9=bad file descriptor
```
I suspected that someone was closing the fd unexpectedly. I confirmed this with a little DTrace script:
```
syscall::write*:entry
/execname == "nomsfs" && arg0 == 11/
{
trace(arg0);
self->yes = 1;
}
syscall::write*:return
/self->yes/
{
printf("%d %d", arg1, errno);
self->yes = 0;
}
syscall::close:entry
/execname == "nomsfs" && arg0 == 11/
{}
```
This showed a `close` preceding the failing `write` and then another `close` on the same fd in the …
> fix spurious failures due to unexpected mountFd closure

- fuse/pathfs/loopback.go
When mounting using relative paths, "touch" on directories fails:
$ loopback b a &
$ cd b
$ mkdir foo
$ touch foo
touch: setting times of 'foo': Not a directory
strace:
[pid 30185] utimensat(0, "a/foo", [{1468441847, 0}, {1468441847, 0}], AT_SYMLINK_NOFOLLOW <unfinished ...>
[...]
[pid 30185] <... utimensat resumed> )   = -1 ENOTDIR (Not a directory)
Change-Id: If78f67fd8cfee946bf1a1112b81dd7fe959afe2b
> loopback: use AT_FDCWD in utimensat call

- fuse/misc.go
- fuse/nodefs/files_darwin.go
- fuse/nodefs/files_linux.go
- fuse/pathfs/loopback_linux.go
- fuse/test/loopback_linux_test.go
syscall.NsecToTimespec is broken for dates before 1970 but works
fine otherwise.
Fix #100 as well and add a testcase.
> loopback: Utimens: enable Nsec precision for dates after 1970

- unionfs/unionfs_xattr_test.go
This first race was easy to find and fix in the tests themselves.
It exposes another race in nodefs.FileSystemConnector where a node's
mount (and therefore, treeLock) is is not the same as the grand-parent
node's is.
Updates #138.
> fix first unionfs test datarace

- fuse/nodefs/inode.go
Inode.Parent() has to take the treeLock before looking
at the parents map.
Fixes https://github.com/hanwen/go-fuse/issues/166
> nodefs: fix data race in Inode.Parent()

- fuse/direntry.go
- fuse/pathfs/loopback.go
- fuse/test/loopback_linux_test.go
When an app in a FUSE mount calls getdents(2), go-fuse receives
READDIR[PLUS] and calls the filesystem's OpenDir function that
returns []DirEntry.
The data returned from getdents(2) contains an inode number for
each directory entry, "d_ino". Until now, struct DirEntry had no
corresponding field and the value passed to the kernel was always
FUSE_UNKNOWN_INO = 0xffffffff
This broke apps that actually look at the d_ino field, like
"find -inum".
This commit adds the "Ino" filed to struct DirEntry. If the field
is not set by the filesystem, it is set to FUSE_UNKNOWN_INO,
as before. Otherwise it is left alone and passed to the kernel.
loopbackFileSystem's OpenDir function is extended to set the inode
number. A test verifies that the returned inode number is sane.
Fixes …
> fuse, loopback: return actual inode numbers from READDIR

- fuse/nodefs/handle.go
- fuse/nodefs/handle_test.go
- fuse/nodefs/inode.go
Reduces Sizeof(nodefs.Inode{}) from 112 to 96 bytes.
The "generation" field in "Inode" is not used anywhere.
"portableHandleMap" has it's own generation field, which
is actually used.
The "check" field, embedded through the "handled" struct,
is checked for zero, but never set.
This is part of an effort to reduce the memory usage of go-fuse
and gocryptfs. Details can be seen at
https://github.com/rfjakob/gocryptfs/issues/132 .
> nodefs: drop unused fields from Inode struct

- fuse/server.go
With golang 1.9, calling WaitMount is necessary to avoid hitting the
deadlock mentioned in #165 in tests where a single process acts as
both the fuse daemon and the client.
Signed-off-by: Shayan Pooya <shayan@arista.com>
> Remove out of date comment

- fuse/request.go
Trivial patch that fixes a blank line in the debug output.
Before:
```
2017/10/03 20:25:56 Dispatch 602: READDIRPLUS, NodeId: 1. data: {Fh 2 off 0 sz 4096  L 0 DIRECTORY,NONBLOCK,0x8000}
2017/10/03 20:25:56 Serialize 602: READDIRPLUS code: OK value:  832 bytes data
2017/10/03 20:25:56 Dispatch 603: GETXATTR, NodeId: 7. data: {sz 0} names: [system.posix_acl_access] 24 bytes
2017/10/03 20:25:56 Serialize 603: GETXATTR code: 61=no data available value:
```
After:
```
2017/10/03 21:02:46 Dispatch 22: READDIRPLUS, NodeId: 1. data: {Fh 2 off 0 sz 4096  L 0 RDONLY,0x8000} 
2017/10/03 21:02:46 Serialize 22: READDIRPLUS code: OK value:  648 bytes data
2017/10/03 21:02:46 Dispatch 23: READDIRPLUS, NodeId: 1. data: {Fh 2 off 4 sz 4096  L 0 RDONLY,0x8000} 
2017/10/03 21:02:46 Serialize 23: …
```
> debug output: fix blank line after READDIRPLUS

- fuse/pathfs/pathfs.go
The function was written with only a single return at
the end, which was elegant, but harder to follow.
Add early returns to handle common cases and add a few
comments.
A functional change is that we now catch when we get
OK with fi == nil and return EINVAL and log a message.
This should not happen and is a bug in the filesystem
implementation.
Passes ./all.bash and the gocryptfs test suite.
> pathfs: simplify pathInode.GetAttr

- fuse/test/loopback_linux_test.go
- fuse/test/xfs_test.go
On mips64le, syscall.Getdents() and struct syscall.Dirent do
not fit together, causing our parseDirents() implementation to
return garbage ( see https://github.com/rfjakob/gocryptfs/issues/200
and https://github.com/golang/go/issues/23624 ).
Switch to unix.Getdents which does not have this problem -
the next Go release with the syscall package fixes is too
far away, and will take time to trickle into distros.
This issue has been reported by Debian maintainer
Felix Lechner.
> Switch from syscall.Getdents to unix.Getdents

- fuse/opcode.go
- fuse/request.go
Set the operationHandlers[op].DecodeIn function and
add xattr name parsing.
SETXATTR is special because it is the only opcode that
takes a file name (the xattr name) and a binary blob
(the xattr value). This was not supported by the
file name parsing code:
* setting FileNames = 1 would lump the xattr name
and value together and truncates the last byte
* setting FileNames = 2 truncated the last xattr
value byte.
This was solved by adding a special-case to parse(),
which seemed less ugly than adding a special-case
InputDebug(), or leaving the truncation as-is.
Before:
2018/05/01 16:47:39 Dispatch 6: SETXATTR, NodeId: 3.  12 bytes
After:
2018/05/01 16:48:36 Dispatch 6: SETXATTR, NodeId: 3. data: {sz 3 f0} names: [user.foo] 12 bytes
The change only affects debug output as doSetXAttr() does …
> fuse: improve SETXATTR debug logging

- fuse/nodefs/fsconnector.go
according to golint, comments of a type must start with the type name  - case sensitive.
> fix minor typo/linter error

- fuse/mount_linux.go
On a Linux system with go-fuse program running as root, the mount is
performed by calling /bin/fusermount, and the unmount is performed with
syscall.Unmount()
This creates a problem on systems (CentOS 6) with a static-but-edited-by-mount
/etc/mtab file.
- fusermount adds a line to mtab when the go-fuse program starts
- syscall.Unmount() doesn't edit the file on program exit
- subsequent invocations of the program fail to mount with:
"Mount fail: fusermount exited with code 256"
Deleting the now-inaccurate mtab entry clears things up.
There's probably a workaround by adding "-n" option so that mount doesn't
edit mtab in the first place, but it's not obvious where to insert that when
starting with the hello.go example.
> syscall-based unmount leaves garbage in /etc/mtab

- .travis.yml
- README.md
- fuse/test/file_lock_test.go
- go.mod
- go.sum
This CL adds support for Go modules, now in preview-mode in Go1.11.
This CL also adds support for continuous integration via Travis-CI (and the obligatory build status badge)
> fuse: add support for Go modules

- fuse/nodefs/fsconnector.go
- fuse/opcode.go
- fuse/print.go
- fuse/server.go
- fuse/test/cachecontrol_test.go
- fuse/types.go
I'm writing a networked filesystem which reads data in 2MB blocks from
remote database. However read requests from the kernel come in much
smaller sizes - for example 4K-128K.
Since it would be very slow to refetch the 2MB block for e.g. every
consecutive 4K reads, a cache for fetched data is needed. A custom cache
would do, however since the kernel already implements pagecache to cache
file data, it is logical to use it directly.
FUSE protocol provides primitives for pagecache control. We already have
support for e.g. invalidating a data region for inode (InodeNotify), but
there is more there. In particular it is possible to store and
retrieve data into/from the kernel cache with "store notify" and
"retrieve notify" messages:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux. …
> Add support for store notify

- fuse/api.go
Current state is: fuse's godoc package-level description is completely
empty because there is a blank link between package-level description
and package clause.
Yes, a user still has to go through api.go and read it in full, but
having at least something for the description is a better start, and
removing one line is easy.
We already do it this way e.g. for nodefs and in other places.
> fuse: A bit better package documentation rendering in godoc

- fuse/pathfs/pathfs.go
gocryptfs user Felix Lechner reported a nil pointer dereference
in GetAttr: https://github.com/rfjakob/gocryptfs/issues/260
The crash is in line
n.setClientInode(fi.Ino)
because fi is nil.
This can happen when file.GetAttr() returns an error code other than
ENOSYS and EBADF. For gocryptfs, this can only happen when an open
file descriptor breaks. In this case it was triggered by a failing
NFS volume.
Fix the crash by erroring out for error codes that are not handled
by the retry-by-path logic.
> pathfs: fix possible nil pointer dereference in GetAttr

- fuse/server.go
@rfjakob reports that after bdca0e6a (Add support for store notify)
build got broken on ARM:
$ GOARCH=arm go build ./example/loopback
fuse/server.go:490:11: constant 4294967295 overflows int
fuse/server.go:492:9: constant 4294967295 overflows int
Fix it by amending "store notify" patch by chunking data into 2GB instead of
full-32bit-range 4GB.
> fuse: Fix build on 32-bit platforms

- fuse/misc.go
- fuse/opcode.go
- fuse/server.go
- fuse/types.go
- it is not NOTIFY_INVAL_DELETE, but just NOTIFY_DELETE as the kernel is
notified of entry being deleted and there is no invalidation here.
uapi/linux/fuse.h does not use "_INVAL_" for NOTIFY_DELETE neither.
- similarly for "notify store/retrieve" _INVAL_ is not appropriate and
neither is used in uapi/linux/fuse.h . However since we took more
explicit approach for "notify store/retrieve" naming (see bdca0e6a
"Add support for store notify") let's also add _CACHE suffix for
"notify store/retrieve" operation names for consistency and for being
less ambiguous.
- for inode/entry invalidation operations, let's use _INVAL_ in internal
_OP_NOTIFY_*, similarly to how it is used in corresponding NOTIFY_*
constant. For example:
_OP_NOTIFY_ENTRY -> _OP_NOTIFY_INVAL_ENTRY	(corresponds to …
> fuse: Correct NOTIFY constants/operation names

- fuse/types.go
for convenience reasons like return values of `fuse.Status` in type FileSystem
e.g. in `Open(name string, flags uint32, context *fuse.Context) (file nodefs.File, code fuse.Status)`
> added syscall.EISDIR constant

- unionfs/timedcache.go
`TimedIntCache` -> `TimedCache`
> Fix a typo in timedcache.go

- fuse/types.go
my fuse implementation connects to another backend. I want users to be able to tell, whether a IO error happens on my fuse implementation itself (because users did some wrong interaction or sth. else) or rather on the backend (because backend itself returns an EIO error, which would be wrongy interpreted if my implementation returned EIO as well).
It's not a MUST, I could still live with the EIO option. But would be very nice.
> added EREMOTEIO constant

- fuse/nodefs/fsconnector.go
- fuse/opcode.go
- fuse/print.go
- fuse/server.go
- fuse/test/cachecontrol_test.go
- fuse/types.go
This patch continues bdca0e6a (Add support for store notify) and adds
corresponding support for counterpart to cache-store - to retrieve an inode
data from kernel cache.
As it was already noted in bdca0e6a, FUSE protocol provides primitives for
pagecache control: to invalidate a data region for inode (notify_inval_inode),
to store data into inode kernel's cache (notify_store), and to retrieve data
from inode kernel's cache (notify_retrieve). For the latter 2 FUSE protocol
messages and brief documentation about semantic can be seen here:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/fuse.h?id=v4.19-rc6-177-gcec4de302c5f#n68
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/fuse.h?id=v4.19-rc6-177-gcec4de30 …
> Add support to retrieve kernel cache (retrieve notify)

- README.md
d1c826d1 ("fuse: increase signal/noise in log messages",
https://github.com/hanwen/go-fuse/pull/249) changed log to use
abbreviations in the name of improving signal/noise ratio. However it
might be not evident offhand what an abbreviation means.
Add a short reference in the readme with the summary on how to read the
log and a short example.
The summary is incomplete - for example I don't describe Fh and other
attributes that d1c826d1 did not change. I propose we review logging
more, e.g. consider doing `Fh X` -> `fX` and maybe similarly for other
fields, and while doing so, also populate/update the summary and example
in the readme. In other words it is good to document current state, but
it is not fixed in stone and can be evolved.
> readme: Add appendix about how to read Go-FUSE debug log output

- fuse/server.go
This makes it clear when (and why) the filesystem was unmounted.
Example output:
```
$ gocryptfs -fg -nosyslog -fusedebug a b
Password:
Decrypting master key
Filesystem mounted and ready.
2019/01/23 21:52:59 rx 2: ACCESS i1 {r}
2019/01/23 21:52:59 tx 2:     OK
2019/01/23 21:52:59 rx 3: LOOKUP i1 [".Trash"] 7b
2019/01/23 21:52:59 tx 3:     OK, {i0 g0 tE=1s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2019/01/23 21:52:59 rx 4: LOOKUP i1 [".Trash-1026"] 12b
2019/01/23 21:52:59 tx 4:     OK, {i0 g0 tE=1s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2019/01/23 21:53:02 received ENODEV (unmount request), thread exiting
2019/01/23 21:53:02 received ENODEV (unmount request), thread exiting
2019/01/23 21:53:02 received ENODEV (unmount request), …
```
> server: print debug message on ENODEV

- fuse/nodefs/fsmount.go
- fuse/nodefs/fsops.go
- fuse/test/nofile_test.go
Since https://git.kernel.org/linus/7678ac5061 FUSE filesystems were allowed to
return ENOSYS from open and, open seeing this, the kernel will not send any
open request anymore and just use Fh=0 for all opened files. This is handy for
filesystems that don't have any per-opened-file state.
However if there is at least one node for which opened files should have
their own state, it is not correct to return ENOSYS from open _ever_, as that
would prevent the kernel to call open on all nodes - in particular on the node
where open needs to create a state associated with the file handle(*).
It is already explicitly documented that Node.Open can return File=nil
in which case filesystem operations like Read and Write will be called
on the node directly. This way a filesystem could try to simulate …
> nodefs: Don't crash on handleless WithFlags opens

- fuse/opcode.go
Small improvement for BATCH_FORGET log output while I was debugging https://github.com/rfjakob/gocryptfs/issues/322 .
------------
Node numbers are now written as "i1234" everywhere except in the
BATCH_FORGET output, fix that. Also show the transaction number
so we can follow where each forget comes from.
As a normal FORGET looks like this:
2019/01/27 14:38:07 rx 1488: FORGET i822 {Nlookup=1}
with the new output, "grep FORGET i1234 " will catch both single forgets
and batch forgets.
Before:
2019/01/20 18:15:31 rx 1372: BATCH_FORGET i0 {Count=3}  48b
2019/01/20 18:15:31 doBatchForget: forgetting 1 of 3: NodeId: 40, Nlookup: 1
2019/01/20 18:15:31 doBatchForget: forgetting 2 of 3: NodeId: 41, Nlookup: 1
2019/01/20 18:15:31 doBatchForget: forgetting 3 of 3: NodeId: 42, Nlookup: 1
After: …
> fuse: improve BATCH_FORGET debug log output

- fuse/nodefs/dir.go
- fuse/nodefs/fsconnector.go
- fuse/nodefs/fsmount.go
- fuse/nodefs/fsops.go
- casting fuse.AttrOut.Attr to fuse.Attr is noop
- casting fileSystemMount.options.Owner to fuse.Owner is noop
- casting fuse.ReadIn.Context to fuse.Context is noop
> nodefs: Drop unneecessary casts

- fuse/nodefs/fsconnector.go
- fuse/nodefs/fsops.go
- fuse/pathfs/pathfs.go
Add a lock that prevents LOOKUP and FORGET from running concurrently.
Locking at this level is a big hammer, but makes sure we don't return
forgotten nodes to the kernel. Problems solved by this lock:
https://github.com/hanwen/go-fuse/issues/168
https://github.com/rfjakob/gocryptfs/issues/322
> Prevent concurrent LOOKUP and FORGET

- fuse/nodefs/fsconnector.go
- fuse/print.go
For example
15:12:42.711011 tx 0: NOTIFY_INVAL_ENTRY, {parent i1 sz 8} "file.txt"
instead of
15:12:42.711011 tx 0: NOTIFY_INVAL_ENTRY, {parent 1 sz 8} "file.txt"
using iX fits into our general logging scheme and makes logs more
self-descriptive.
> fuse: When parent or child is inode, log it as iX instead of X

- fuse/opcode.go
After Linux VFS was enhanced to be able to do several lookups and
readdirs in parallel, FUSE client in Linux, in fear to break existing
filesystems, explicitly reverted it back to be serial in FUSE exchange
and requested filesystems to indicate via CAP_PARALLEL_DIROPS flag that
the filesystem server is ready to handle parallel lookup and readdir
requests.
https://git.kernel.org/linus/5c672ab3f0
We should be ready to handle and we provide MountOptions.SingleThreaded
for those filesystems, which are not ready to handle requests in
parallel.
> fuse: Enable parallel lookup and readdir by default

- nodefs/default.go
Trying to save you some grunt work.
------------------
Add stub implementations for the rest of the methods from the
Operations interface, and add a compile-time check that we don't
have missed any.
> DefaultOperations: implement the rest of the Operations methods

- fuse/types_darwin.go
We usually were off by a factor of 256.
Fixes https://github.com/rfjakob/gocryptfs/issues/375 , https://github.com/rfjakob/gocryptfs/issues/274
> fuse: fix free space reporting on Darwin

- fuse/types.go
FOPEN_CACHE_DIR was added in Linux 4.19:
https://git.kernel.org/linus/6433b8998a
> fuse: Add FOPEN_CACHE_DIR

- nodefs/dirstream_linux.go
The old code searched for the first non-null byte from the end of
the slice. This assumes that all bytes after the name are initialized
to zero, which does not hold true on Linux 4.15.
Instead, search for the first null byte from the start of the slice,
which is guaranteed by man(3) readdir.
Fixes https://github.com/hanwen/go-fuse/issues/287
> dirstream_linux: fix zero terminator search

- fuse/opcode.go
When kernel sends WRITE request it sends with it file handle, offset,
size etc. We were not printing all this. Compare e.g. debug output
sample for TestUtimesNano before and after the patch.
before:
rx 8: CREATE i1 {0100600 [CREAT,TRUNC,WRONLY,0x8000] (00)} ["hello.txt"] 10b
tx 8:     OK, {i3 g2 {M0100600 SZ=0 L=1 1000:1000 B0*4096 i0:733462 A 1556038355.426630 M 1556038355.426630 C 1556038355.426630} &{2 0 0}}
rx 9: GETXATTR i3 {sz 0} ["security.capability"] 20b
tx 9:     61=no data available
rx 10: WRITE i3  3b							<-- NOTE
tx 10:     OK
after:
rx 8: CREATE i1 {0100600 [WRONLY,CREAT,TRUNC,0x8000] (00)} ["hello.txt"] 10b
tx 8:     OK, {i3 g2 {M0100600 SZ=0 L=1 1000:1000 B0*4096 i0:736300 A 1556038379.359197 M 1556038379.359197 C 1556038379.359197} &{2 0 0}}
rx 9: GETXATTR i3 {sz 0} …
> fuse: Don't skip WRITE details in debug output

- fuse/print.go
- fuse/types.go
FOPEN_STREAM, together with FOPEN_NONSEEKABLE must be used on
stream-like file handles that provide both read and write to avoid
hitting deadlock in the kernel.
Please see the following kernel patch for details on how the deadlock
can happen:
https://git.kernel.org/linus/10dce8af3422
Adding FOPEN_STREAM to kernel FUSE is still in the works, but is likely
to enter mainline kernel one way or another:
https://lore.kernel.org/linux-fsdevel/dc47c061f20c464ccf46b43822b062dca6486e90.1553637462.git.kirr@nexedi.com/
https://lore.kernel.org/linux-fsdevel/CAHk-=whQQdoQsgEx1vO7OkfPDcV5hurPnMRLgzfXAPN63n5Sbg@mail.gmail.com/
Here is example for FOPEN_STREAM usage:
https://lab.nexedi.com/kirr/wendelin.core/blob/7783ecf4/wcfs/misc.go#L327-335
https://lab.nexedi.com/kirr/wendelin.core/blob/7783ecf4/wcfs/mi …
> fuse: Add FOPEN_STREAM
